version: '3.4'

services:
  tests-ut:
    image: ${TESTS_IMAGE:?err}
    volumes:
      - ${SOURCE_DIR:?err}/knowledge_gpt:/app/knowledge_gpt
      - ${SOURCE_DIR:?err}/tests:/app/tests
      - ${SOURCE_DIR:?err}/resources:/app/resources
      - ${SOURCE_DIR:?err}/.coveragerc:/app/.coveragerc
    command: >
      bash -c "coverage run -m pytest . --maxfail=3
      && coverage report
      && coverage html --fail-under=55
      || (echo ERROR Tests failed or Coverage under target! && exit 1)"


  dev-server:
    image: ${DEV_IMAGE:?err}
    ports:
      - 8501:8501
    volumes:
      - ${SOURCE_DIR:?err}/knowledge_gpt:/app/knowledge_gpt
    command: ["bash", "-c", "pwd && python -m streamlit run knowledge_gpt/main.py --server.port=8501 --server.address=0.0.0.0"]
